void main( 	float2 texCoord0: TEXCOORD0,
			float2 texCoord1: TEXCOORD1,
			float2 texCoord2: TEXCOORD2,
			float4 colour: COLOR,
			out float4 fragColor: COLOR,
			uniform sampler2D diffuseMap: register(s0)
		)
{
	float red = tex2D(diffuseMap, texCoord0.xy).r;
	float green = tex2D(diffuseMap, texCoord1.xy).g;
	float blue = tex2D(diffuseMap, texCoord2.xy).b;
	
	fragColor = float4(red, green, blue, 1.0) * colour;

}