//-----------------------------------------------------------------------------
// Program Type: Fragment shader
// Language: cg
// Created by Ogre RT Shader Generator. All rights reserved.
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
//                         PROGRAM DEPENDENCIES
//-----------------------------------------------------------------------------
#include "FFPLib_Common.cg"
#include "SGXLib_PerPixelLighting.cg"
#include "FFPLib_Texturing.cg"

//-----------------------------------------------------------------------------
//                         GLOBAL PARAMETERS
//-----------------------------------------------------------------------------

float4	derived_ambient_light_colour;
float4	surface_specular_colour;
float4	surface_emissive_colour;
float4	derived_scene_colour;
float	surface_shininess;
sampler2D	gTextureSampler0 : register(s0);

//-----------------------------------------------------------------------------
// Function Name: main
// Function Desc: Pixel Program Entry point
//-----------------------------------------------------------------------------
void main
	(
	 in float4	iColor_0 : COLOR, 
	 in float3	iTexcoord3_0 : TEXCOORD0, 
	 in float2	iTexcoord2_1 : TEXCOORD1, 
	 out float4	oColor_0 : COLOR
	)
{
	float4	lLocalParam_0;
	float4	lPerPixelDiffuse;
	float4	texel_0;
	float4	source1;
	float4	source2;

	FFP_Construct(0.0, 0.0, 0.0, 0.0, lLocalParam_0);

	FFP_Assign(iColor_0, oColor_0);

	FFP_Assign(derived_scene_colour, lPerPixelDiffuse);

	FFP_Assign(lPerPixelDiffuse, iColor_0);

	FFP_Assign(iColor_0, oColor_0);

	FFP_SampleTexture(gTextureSampler0, iTexcoord2_1, texel_0);

	FFP_Assign(texel_0, source1);

	FFP_Assign(iColor_0, source2);

	FFP_Modulate(source1, source2, oColor_0);

	FFP_Add(oColor_0.xyz, lLocalParam_0.xyz, oColor_0.xyz);
}

