//-----------------------------------------------------------------------------
// Program Type: Fragment shader
// Language: cg
// Created by Ogre RT Shader Generator. All rights reserved.
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
//                         PROGRAM DEPENDENCIES
//-----------------------------------------------------------------------------
#include "FFPLib_Common.cg"
#include "FFPLib_Texturing.cg"

//-----------------------------------------------------------------------------
//                         GLOBAL PARAMETERS
//-----------------------------------------------------------------------------

sampler2D	gTextureSampler0 : register(s0);

//-----------------------------------------------------------------------------
// Function Name: main
// Function Desc: Pixel Program Entry point
//-----------------------------------------------------------------------------
void main
	(
	 in float2	iTexcoord2_0 : TEXCOORD0, 
	 out float4	oColor_0 : COLOR
	)
{
	float4	lLocalParam_0;
	float4	lLocalParam_1;
	float4	texel_0;
	float4	source1;
	float4	source2;

	FFP_Construct(1.0, 1.0, 1.0, 1.0, lLocalParam_0);

	FFP_Construct(0.0, 0.0, 0.0, 0.0, lLocalParam_1);

	FFP_Assign(lLocalParam_0, oColor_0);

	FFP_SampleTexture(gTextureSampler0, iTexcoord2_0, texel_0);

	FFP_Assign(texel_0, source1);

	FFP_Assign(lLocalParam_0, source2);

	FFP_Modulate(source1, source2, oColor_0);

	FFP_Add(oColor_0.xyz, lLocalParam_1.xyz, oColor_0.xyz);
}

